### PR TITLE
Update existing usagse with faster "has flag" method

### PR DESCRIPTION
**Pull request by frenzibyte**
As per https://github.com/ppy/osu-framework/pull/4218.

### CODE REVIEW

**Comment by swoolcock** [comment]
Surely there are more cases than this that you could change.  Beatmap conversion performance is not an issue, gameplay is.

**Comment by frenzibyte** [comment]
Just getting rid of how that method turned out to be, not sure I see the issue?

**Comment by swoolcock** [comment]
My point is, can this PR be expanded more?

**Comment by frenzibyte** [comment]
Can't see any on my end, nope.

**Pull request merged**
